### PR TITLE
Anylinux sharun packaging

### LINKED ISSUE #9: AppImage fails to start on Fedora 43: missing libgee-0.8.so.2
When attempting to run `AppManager-3.0.0-x86_64.AppImage` on Fedora 43, the application fails to launch due to a missing shared library dependency.

It appears `libgee` is not bundled within the AppImage, and it is not installed by default on a standard Fedora 43 workstation installation.
It's an issue for Fedora atomic.

```sh
/tmp/.mount_AppManLIFljE/usr/bin/app-manager: error while loading shared libraries: libgee-0.8.so.2: cannot open shared object file: No such file or directory
```

### PR DESCRIPTION
**Pull request by kem-a**
* Enhance artifact naming for AnyLinux AppImage uploads and cleanup intermediate artifacts (07db3b0)
* Refactor packaging and distributoin flow. Add AnyLinux support with sharun (c25e272). Fixes #9  #11  #13 and possibly #10

### CODE REVIEW

File: scripts/make-anyimage.sh [hunk 1]
```diff
@@ -0,0 +1,156 @@
...
+# quick-sharun will auto-detect GTK4, libadwaita, and all their deps.
+# The helper tools (dwarfs, zsync2, 7z) are static binaries installed
+# by meson to /usr/bin — they need to be passed explicitly since the
+# app invokes them as child processes, not via dynamic linking.
+"$QS" \
+    /usr/bin/app-manager \
+    /usr/bin/dwarfsextract \
+    /usr/bin/dwarfsck \
+    /usr/bin/zsync2 \
+    /usr/bin/7z
```
Comment (Samueru-sama) [inline scripts/make-anyimage.sh]: On archlinux `/usr/bin/7z` is a shell script that is coded to run `exec /usr/lib/7zip/7z "$@"`, so you most likely need to add that file instead.

With vala apps you may need to pass `/usr/share/vala` to `quick-sharun` btw

Also if this app uses glib networking, you need to pass a few libs manully, [see this](https://github.com/pkgforge-dev/ProtonPlus-AppImage/blob/4b95c7793e7bfb933ccbf567cb9141d693415c34/make-appimage.sh#L20-L23)
